apiVersion: apps/v1 
kind: Deployment
metadata:
  name: soongon-custapp
  labels: 
     app: custapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: custapp

  template:
    metadata:
      labels:
        app: custapp
    spec:
      containers:
      - name: custapp
        image: soongon/custapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1