---
- hosts: ansible_server
  tasks:
  - name: create docker image
    command: docker build -t custapp:latest .





---
- hosts: docker_host
  tasks:
  - name: stop existing container
    command: docker stop custapp-container
    ignore_errors: yes

  - name: remove the container
    command: docker rm custapp-container
    ignore_errors: yes

  - name: remove image
    command: docker rmi soongon/custapp:latest
     ignore_errors: yes
   
  - name: create container
    command: docker run -d --name custapp-container -p 8081:8080 soongon/custapp:latest
    